version: '3'
services: 
    gateway: 
        image: nginx:latest
        ports: 
            - "80:80"
        volumes:
            - ./react-web/build:/srv/www
            - ./default.conf:/etc/nginx/conf.d/default.conf